// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/forgot-password": {
    params: {};
  };
  "/reset-password/:token": {
    params: {
      "token": string;
    };
  };
  "/auth/google": {
    params: {};
  };
  "/auth/google/callback": {
    params: {};
  };
  "/logout": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/profile": {
    params: {};
  };
  "/profile/edit": {
    params: {};
  };
  "/trips/new": {
    params: {};
  };
  "/trips/:tripId": {
    params: {
      "tripId": string;
    };
  };
  "/trips/:tripId/edit": {
    params: {
      "tripId": string;
    };
  };
  "/trips/:tripId/memories/new": {
    params: {
      "tripId": string;
    };
  };
  "/trips/:tripId/memories/:memoryId": {
    params: {
      "tripId": string;
      "memoryId": string;
    };
  };
  "/trips/:tripId/memories/:memoryId/edit": {
    params: {
      "tripId": string;
      "memoryId": string;
    };
  };
  "/trips/:tripId/expenses": {
    params: {
      "tripId": string;
    };
  };
  "/:username": {
    params: {
      "username": string;
    };
  };
  "/:username/:tripSlug": {
    params: {
      "username": string;
      "tripSlug": string;
    };
  };
  "/:username/:tripSlug/:memorySlug": {
    params: {
      "username": string;
      "tripSlug": string;
      "memorySlug": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/register" | "/forgot-password" | "/reset-password/:token" | "/auth/google" | "/auth/google/callback" | "/logout" | "/dashboard" | "/profile" | "/profile/edit" | "/trips/new" | "/trips/:tripId" | "/trips/:tripId/edit" | "/trips/:tripId/memories/new" | "/trips/:tripId/memories/:memoryId" | "/trips/:tripId/memories/:memoryId/edit" | "/trips/:tripId/expenses" | "/:username" | "/:username/:tripSlug" | "/:username/:tripSlug/:memorySlug";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "pages/auth/login.tsx": {
    id: "pages/auth/login";
    page: "/login";
  };
  "pages/auth/register.tsx": {
    id: "pages/auth/register";
    page: "/register";
  };
  "pages/auth/forgot-password.tsx": {
    id: "pages/auth/forgot-password";
    page: "/forgot-password";
  };
  "pages/auth/reset-password.tsx": {
    id: "pages/auth/reset-password";
    page: "/reset-password/:token";
  };
  "pages/auth/google.tsx": {
    id: "pages/auth/google";
    page: "/auth/google";
  };
  "pages/auth/google-callback.tsx": {
    id: "pages/auth/google-callback";
    page: "/auth/google/callback";
  };
  "pages/auth/logout.tsx": {
    id: "pages/auth/logout";
    page: "/logout";
  };
  "components/layout/app-shell.tsx": {
    id: "components/layout/app-shell";
    page: "/dashboard" | "/profile" | "/profile/edit" | "/trips/new" | "/trips/:tripId" | "/trips/:tripId/edit" | "/trips/:tripId/memories/new" | "/trips/:tripId/memories/:memoryId" | "/trips/:tripId/memories/:memoryId/edit" | "/trips/:tripId/expenses";
  };
  "pages/dashboard.tsx": {
    id: "pages/dashboard";
    page: "/dashboard";
  };
  "pages/profile/profile.tsx": {
    id: "pages/profile/profile";
    page: "/profile";
  };
  "pages/profile/profile-edit.tsx": {
    id: "pages/profile/profile-edit";
    page: "/profile/edit";
  };
  "pages/trips/trip-new.tsx": {
    id: "pages/trips/trip-new";
    page: "/trips/new";
  };
  "pages/trips/trip-detail.tsx": {
    id: "pages/trips/trip-detail";
    page: "/trips/:tripId";
  };
  "pages/trips/trip-edit.tsx": {
    id: "pages/trips/trip-edit";
    page: "/trips/:tripId/edit";
  };
  "pages/trips/memory-new.tsx": {
    id: "pages/trips/memory-new";
    page: "/trips/:tripId/memories/new";
  };
  "pages/trips/memory-detail.tsx": {
    id: "pages/trips/memory-detail";
    page: "/trips/:tripId/memories/:memoryId";
  };
  "pages/trips/memory-edit.tsx": {
    id: "pages/trips/memory-edit";
    page: "/trips/:tripId/memories/:memoryId/edit";
  };
  "pages/trips/expenses.tsx": {
    id: "pages/trips/expenses";
    page: "/trips/:tripId/expenses";
  };
  "pages/public/user-profile.tsx": {
    id: "pages/public/user-profile";
    page: "/:username";
  };
  "pages/public/trip-public.tsx": {
    id: "pages/public/trip-public";
    page: "/:username/:tripSlug";
  };
  "pages/public/memory-public.tsx": {
    id: "pages/public/memory-public";
    page: "/:username/:tripSlug/:memorySlug";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "pages/auth/login": typeof import("./app/pages/auth/login.tsx");
  "pages/auth/register": typeof import("./app/pages/auth/register.tsx");
  "pages/auth/forgot-password": typeof import("./app/pages/auth/forgot-password.tsx");
  "pages/auth/reset-password": typeof import("./app/pages/auth/reset-password.tsx");
  "pages/auth/google": typeof import("./app/pages/auth/google.tsx");
  "pages/auth/google-callback": typeof import("./app/pages/auth/google-callback.tsx");
  "pages/auth/logout": typeof import("./app/pages/auth/logout.tsx");
  "components/layout/app-shell": typeof import("./app/components/layout/app-shell.tsx");
  "pages/dashboard": typeof import("./app/pages/dashboard.tsx");
  "pages/profile/profile": typeof import("./app/pages/profile/profile.tsx");
  "pages/profile/profile-edit": typeof import("./app/pages/profile/profile-edit.tsx");
  "pages/trips/trip-new": typeof import("./app/pages/trips/trip-new.tsx");
  "pages/trips/trip-detail": typeof import("./app/pages/trips/trip-detail.tsx");
  "pages/trips/trip-edit": typeof import("./app/pages/trips/trip-edit.tsx");
  "pages/trips/memory-new": typeof import("./app/pages/trips/memory-new.tsx");
  "pages/trips/memory-detail": typeof import("./app/pages/trips/memory-detail.tsx");
  "pages/trips/memory-edit": typeof import("./app/pages/trips/memory-edit.tsx");
  "pages/trips/expenses": typeof import("./app/pages/trips/expenses.tsx");
  "pages/public/user-profile": typeof import("./app/pages/public/user-profile.tsx");
  "pages/public/trip-public": typeof import("./app/pages/public/trip-public.tsx");
  "pages/public/memory-public": typeof import("./app/pages/public/memory-public.tsx");
};